=== LHNCBC/lforms-validator/lforms-form-schema-v0.1.0.json
{
  "id": "lforms-form-schema-v0.1.0#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "code": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "templateOptions": {
      "$ref": "#/definitions/templateOptions"
    },
    "items": {
      "type": "array",
      "items": {
        "$ref": "lforms-item-schema-v0.1.0.json"
      }
    }
  },
  "required": [
    "name",
    "items"
  ],
  "definitions": {
    "templateOptions": {
      "type": "object",
      "properties": {
        "showQuestionCode": {"type": "boolean"},
        "showCodingInstruction": {"type": "boolean"},
        "tabOnInputFieldsOnly": {"type": "boolean"},
        "hideCheckBoxes": {"type": "boolean"},
        "allowMultipleEmptyRepeatingItems": {"type": "boolean"},
        "allowHTMLInstructions": {"type": "boolean"},
        "useAnimation": {"type": "boolean"},
        "obrHeader": {"type": "boolean"},
        "hideHeader": {"type": "boolean"},
        "displayControl": {
          "type": ["object", "null"],
          "properties": {
            "questionLayout": {
              "$ref": "lforms-item-schema-v0.1.0.json#/definitions/questionLayout"
            }
          },
          "additionalProperties": false
        },
        "obxTableColumns": {
          "type": ["array", "null"],
          "items": {
            "$ref": "#/definitions/obxTableColumn"
          }
        },
        "obrItems": {
          "type": ["array", "null"],
          "items": {
            "$ref": "#/definitions/obrItem"
          }
        }
      },
      "additionalProperties": false
    },
    "obxTableColumn": {
      "type": "object",
      "properties": {
        "name": {
          "type": ["string", "null"]
        },
        "displayControl": {
          "type": ["object", "null"],
          "properties": {
            "colCSS": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "obrItem": {
      "type": "object",
      "properties": {
        "question": {"type": "string"},
        "dataType": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/dataType"}
          ]
        },
        "displayControl": {
          "type": "object",
          "properties": {
            "colCSS": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            },
            "css": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            }
          },
          "additionalProperties": false
        },
        "answerCardinality": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/cardinality"}
          ]
        },
        "answers": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/answers"}
          ]
        }
      },
      "additionalProperties": false
    }
  }
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/70298-5.json
{
  "type": "LOINC",
  "code": "70298-5",
  "name": "Mineral metabolism panel",
  "items": [
    {
      "questionCode": "1751-7",
      "localQuestionCode": "RQMT_296",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Albumin SerPl-mCnc",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "33882-2",
      "localQuestionCode": "RQMT_297",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Collect Date XXX",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "68900-0",
      "localQuestionCode": "RQMT_299",
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Albumin Lab Method",
      "answers": [
        {
          "label": null,
          "code": "LA17963-2",
          "text": "BCG - bromocresol green",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA17964-0",
          "text": "BCP - bromocresol purple",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "2777-1",
      "localQuestionCode": "RQMT_315",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Phosphate SerPl-mCnc",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "33882-2",
      "localQuestionCode": "RQMT_316",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Collect Date XXX",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "46099-8",
      "localQuestionCode": "RQMT_317",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Calcium Album cor SerPl-mCnc",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "33882-2",
      "localQuestionCode": "RQMT_318",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Collect Date XXX",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "17861-6",
      "localQuestionCode": "RQMT_319",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Calcium SerPl-mCnc",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "33882-2",
      "localQuestionCode": "RQMT_320",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Collect Date XXX",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/72068-0.json
{
  "type": "LOINC",
  "code": "72068-0",
  "name": "Iron panel",
  "items": [
    {
      "questionCode": "72067-2",
      "localQuestionCode": null,
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Iron prescription current",
      "answers": [
        {
          "label": null,
          "code": "LA32-8",
          "text": "No",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA33-6",
          "text": "Yes",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "71465-9",
      "localQuestionCode": "ESRD.RQMT_306",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Date prescription changed",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "72066-4",
      "localQuestionCode": null,
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Intravenous iron prescribed",
      "answers": [
        {
          "label": null,
          "code": "LA32-8",
          "text": "No",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA33-6",
          "text": "Yes",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "72065-6",
      "localQuestionCode": null,
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Type intravenous iron prescribed",
      "answers": [
        {
          "label": null,
          "code": "LA18912-8",
          "text": "Iron dextran (Dexferrum, Infed)",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA18913-6",
          "text": "Sodium ferric gluconate (Ferrlecit)",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA18914-4",
          "text": "Iron sucrose (Venofer)",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA46-8",
          "text": "Other",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "65818-7",
      "localQuestionCode": null,
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Medication Dose-mCnc",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "72064-9",
      "localQuestionCode": null,
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Oral iron prescribed",
      "answers": [
        {
          "label": null,
          "code": "LA32-8",
          "text": "No",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA33-6",
          "text": "Yes",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "72063-1",
      "localQuestionCode": null,
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Type oral iron prescribed",
      "answers": [
        {
          "label": null,
          "code": "LA18909-4",
          "text": "Ferrous fumarate (Feostat, Femiron)",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA18910-2",
          "text": "Ferrous sulfate (Feosol, FerIron)",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA18911-0",
          "text": "Ferrous gluconate (Ferate, Fergon, Ferralet, Simron)",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA46-8",
          "text": "Other",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/48543-3.json
{
  "type": "LOINC",
  "code": "48543-3",
  "name": "GDS.short Panel",
  "items": [
    {
      "questionCode": "48512-8",
      "question": "Are you basically satisfied with your life GDS",
      "answers": [
        {
          "text": "Yes -- 0",
          "code": "LA33-6",
          "score": 0
        },
        {
          "text": "No -- 1",
          "code": "LA32-8",
          "score": 1
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48513-6",
      "question": "Have you dropped many of your activities and interests GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48514-4",
      "question": "Do you feel that your life is empty GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48515-1",
      "question": "Do you often get bored GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48518-5",
      "question": "Are you in good spirits most of the time GDS",
      "answers": [
        {
          "text": "Yes -- 0",
          "code": "LA33-6",
          "score": 0
        },
        {
          "text": "No -- 1",
          "code": "LA32-8",
          "score": 1
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48519-3",
      "question": "Are you afraid that something bad is going to happen to you GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48520-1",
      "question": "Do you feel happy most of the time GDS",
      "answers": [
        {
          "text": "Yes -- 0",
          "code": "LA33-6",
          "score": 0
        },
        {
          "text": "No -- 1",
          "code": "LA32-8",
          "score": 1
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48521-9",
      "question": "Do you often feel helpless GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48523-5",
      "question": "Do you prefer to stay at home, rather than going out and doing new things GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48525-0",
      "question": "Do you feel you have more problems with memory than most GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48526-8",
      "question": "Do you think it is wonderful to be alive now GDS",
      "answers": [
        {
          "text": "Yes -- 0",
          "code": "LA33-6",
          "score": 0
        },
        {
          "text": "No -- 1",
          "code": "LA32-8",
          "score": 1
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48528-4",
      "question": "Do you feel pretty worthless the way you are now GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48532-6",
      "question": "Do you feel full of energy GDS",
      "answers": [
        {
          "text": "Yes -- 0",
          "code": "LA33-6",
          "score": 0
        },
        {
          "text": "No -- 1",
          "code": "LA32-8",
          "score": 1
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48533-4",
      "question": "Do you feel that your situation is hopeless GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "48534-2",
      "question": "Do you think that most people are better off than you are GDS",
      "answers": [
        {
          "text": "Yes -- 1",
          "code": "LA33-6",
          "score": 1
        },
        {
          "text": "No -- 0",
          "code": "LA32-8",
          "score": 0
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "formula": {
        "name": "SCORE",
        "value": []
      },
      "questionCode": "48545-8",
      "question": "Geriatric depression scale (GDS) short version total",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/38228-3.json
{
  "type": "LOINC",
  "code": "38228-3",
  "name": "Braden scale skin assessment panel",
  "items": [
    {
      "questionCode": "38222-6",
      "question": "Sensory perception Braden scale",
      "answers": [
        {
          "text": "Completely limited -- 1",
          "code": "LA9603-7",
          "score": 1
        },
        {
          "text": "Very limited -- 2",
          "code": "LA9604-5",
          "score": 2
        },
        {
          "text": "Slightly limited -- 3",
          "code": "LA9605-2",
          "score": 3
        },
        {
          "text": "No impairment -- 4",
          "code": "LA9606-0",
          "score": 4
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38229-1",
      "question": "Moisture exposure Braden scale",
      "answers": [
        {
          "text": "Constantly moist -- 1",
          "code": "LA9607-8",
          "score": 1
        },
        {
          "text": "Very moist -- 2",
          "code": "LA9608-6",
          "score": 2
        },
        {
          "text": "Occasionally moist -- 3",
          "code": "LA9609-4",
          "score": 3
        },
        {
          "text": "Rarely moist -- 4",
          "code": "LA9610-2",
          "score": 4
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38223-4",
      "question": "Physical activity Braden scale",
      "answers": [
        {
          "text": "Bedfast -- 1",
          "code": "LA6742-6",
          "score": 1
        },
        {
          "text": "Chairfast -- 2",
          "code": "LA9611-0",
          "score": 2
        },
        {
          "text": "Walks occasionally -- 3",
          "code": "LA9612-8",
          "score": 3
        },
        {
          "text": "Walks frequently -- 4",
          "code": "LA9613-6",
          "score": 4
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38224-2",
      "question": "Physical mobility Braden scale",
      "answers": [
        {
          "text": "Completely immobile -- 1",
          "code": "LA9614-4",
          "score": 1
        },
        {
          "text": "Very limited -- 2",
          "code": "LA9604-5",
          "score": 2
        },
        {
          "text": "Slightly limited -- 3",
          "code": "LA9605-2",
          "score": 3
        },
        {
          "text": "No limitation -- 4",
          "code": "LA120-8",
          "score": 4
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38225-9",
      "question": "Nutrition intake pattern Braden scale",
      "answers": [
        {
          "text": "Very poor -- 1",
          "code": "LA9615-1",
          "score": 1
        },
        {
          "text": "Probably inadequate -- 2",
          "code": "LA9616-9",
          "score": 2
        },
        {
          "text": "Adequate -- 3",
          "code": "LA8913-1",
          "score": 3
        },
        {
          "text": "Excellent -- 4",
          "code": "LA9206-9",
          "score": 4
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38226-7",
      "question": "Friction & sheer Braden scale",
      "answers": [
        {
          "text": "Problem -- 1",
          "code": "LA9617-7",
          "score": 1
        },
        {
          "text": "Potential problem -- 2",
          "code": "LA9618-5",
          "score": 2
        },
        {
          "text": "No apparent problem -- 3",
          "code": "LA9619-3",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "formula": {
        "name": "SCORE",
        "value": []
      },
      "questionCode": "38227-5",
      "question": "Braden scale total score",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}
