=== LHNCBC/lforms-validator/lforms-form-schema-v0.1.0.json
{
  "id": "lforms-form-schema-v0.1.0#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "code": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "templateOptions": {
      "$ref": "#/definitions/templateOptions"
    },
    "items": {
      "type": "array",
      "items": {
        "$ref": "lforms-item-schema-v0.1.0.json"
      }
    }
  },
  "required": [
    "name",
    "items"
  ],
  "definitions": {
    "templateOptions": {
      "type": "object",
      "properties": {
        "showQuestionCode": {"type": "boolean"},
        "showCodingInstruction": {"type": "boolean"},
        "tabOnInputFieldsOnly": {"type": "boolean"},
        "hideCheckBoxes": {"type": "boolean"},
        "allowMultipleEmptyRepeatingItems": {"type": "boolean"},
        "allowHTMLInstructions": {"type": "boolean"},
        "useAnimation": {"type": "boolean"},
        "obrHeader": {"type": "boolean"},
        "hideHeader": {"type": "boolean"},
        "displayControl": {
          "type": ["object", "null"],
          "properties": {
            "questionLayout": {
              "$ref": "lforms-item-schema-v0.1.0.json#/definitions/questionLayout"
            }
          },
          "additionalProperties": false
        },
        "obxTableColumns": {
          "type": ["array", "null"],
          "items": {
            "$ref": "#/definitions/obxTableColumn"
          }
        },
        "obrItems": {
          "type": ["array", "null"],
          "items": {
            "$ref": "#/definitions/obrItem"
          }
        }
      },
      "additionalProperties": false
    },
    "obxTableColumn": {
      "type": "object",
      "properties": {
        "name": {
          "type": ["string", "null"]
        },
        "displayControl": {
          "type": ["object", "null"],
          "properties": {
            "colCSS": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "obrItem": {
      "type": "object",
      "properties": {
        "question": {"type": "string"},
        "dataType": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/dataType"}
          ]
        },
        "displayControl": {
          "type": "object",
          "properties": {
            "colCSS": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            },
            "css": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            }
          },
          "additionalProperties": false
        },
        "answerCardinality": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/cardinality"}
          ]
        },
        "answers": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/answers"}
          ]
        }
      },
      "additionalProperties": false
    }
  }
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/55418-8.json
{
  "type": "LOINC",
  "code": "55418-8",
  "name": "Weight & height tracking panel",
  "items": [
    {
      "questionCode": "29463-7",
      "question": "My body weight",
      "dataType": "NM",
      "units": [
        {
          "name": "pounds",
          "code": 2776
        },
        {
          "name": "kilograms",
          "code": 5770
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8352-7",
      "question": "Clothing worn during measure",
      "answers": [
        {
          "text": "Underwear or less",
          "code": "LA11871-3"
        },
        {
          "text": "Street clothes, no shoes",
          "code": "LA11872-1"
        },
        {
          "text": "Street clothes & shoes",
          "code": "LA11873-9"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8302-2",
      "question": "My body height",
      "dataType": "NM",
      "units": [
        {
          "name": "inches",
          "code": 5564
        },
        {
          "name": "feet",
          "code": 5827
        },
        {
          "name": "centimeters",
          "code": 5828
        },
        {
          "name": "meters",
          "code": 5829
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "formula": {
        "name": "BMI",
        "value": [
          "29463-7",
          "8302-2"
        ]
      },
      "questionCode": "39156-5",
      "question": "Body mass index (BMI) [Ratio]",
      "dataType": null,
      "units": [
        {
          "name": "kg/m2",
          "code": 5790
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8361-8",
      "question": "Body position with respect to gravity",
      "answers": [
        {
          "text": "Sitting",
          "code": "LA11868-9"
        },
        {
          "text": "Lying",
          "code": "LA11869-7"
        },
        {
          "text": "Standing",
          "code": "LA11870-5"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/44249-1.json
{
  "type": "LOINC",
  "code": "44249-1",
  "name": "PHQ-9 depression survey",
  "items": [
    {
      "questionCode": "44257-4",
      "question": "PHQ-9.problem panel Reported PHQ-9",
      "dataType": null,
      "units": [],
      "header": true,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44250-9",
      "question": "Little interest or pleasure in doing things in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44255-8",
      "question": "Feeling down, depressed, or hopeless in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44259-0",
      "question": "Trouble falling or staying asleep, or sleeping too much in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44254-1",
      "question": "Feeling tired or having little energy in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44251-7",
      "question": "Poor appetite or overeating in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44258-2",
      "question": "Feeling bad about yourself - or that you are a failure or have let yourself or your family down in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44252-5",
      "question": "Trouble concentrating on things, such as reading the newspaper or watching television in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44253-3",
      "question": "Moving or speaking so slowly that other people could have noticed. Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44260-8",
      "question": "Thoughts that you would be better off dead, or of hurting yourself in some way in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not at all -- 0",
          "code": "LA6568-5",
          "score": 0
        },
        {
          "text": "Several days -- 1",
          "code": "LA6569-3",
          "score": 1
        },
        {
          "text": "More than half the days -- 2",
          "code": "LA6570-1",
          "score": 2
        },
        {
          "text": "Nearly every day -- 3",
          "code": "LA6571-9",
          "score": 3
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "formula": {
        "name": "SCORE",
        "value": []
      },
      "questionCode": "44261-6",
      "question": "PHQ-9 total score Reported PHQ-9",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "44256-6",
      "question": "Perceived difficulty in last 2 weeks Reported PHQ-9",
      "answers": [
        {
          "text": "Not difficult at all",
          "code": "LA6572-7"
        },
        {
          "text": "Somewhat difficult",
          "code": "LA6573-5"
        },
        {
          "text": "Very difficult",
          "code": "LA6575-0"
        },
        {
          "text": "Extremely difficult",
          "code": "LA6574-3"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/34552-0.json
{
  "type": "LOINC",
  "code": "34552-0",
  "name": "Heart ultrasound (echocardiogram)",
  "items": [
    {
      "questionCode": "18010-9",
      "question": "Aorta Diameter by US",
      "dataType": "NM",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "18018-2",
      "question": "Left ventricular outflow tract Diameter by US",
      "dataType": "NM",
      "units": [
        {
          "name": "centimeters",
          "code": 1172
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "20307-5",
      "question": "Right ventricular outflow tract Diameter by US 2D",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "29468-6",
      "question": "Left atrial Diameter anterior-posterior systole by US 2D",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "18083-6",
      "question": "Left ventricular Internal diameter minor axis diastole by US 2D",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "18085-1",
      "question": "Left ventricular Internal diameter minor axis systole by US 2D",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "29442-1",
      "question": "Left ventricular posterior wall Thickness diastole by US 2D",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "29430-6",
      "question": "Interventricular septum Thickness diastole by US 2D",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8806-2",
      "question": "Left ventricular Ejection fraction by 2D echo",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "29434-8",
      "question": "Left ventricular Fractional shortening minor axis by US 2D",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "18147-9",
      "question": "Central cardiovascular Study observation by US",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/38213-5.json
{
  "type": "LOINC",
  "code": "38213-5",
  "name": "FLACC Pain Assessment Panel",
  "items": [
    {
      "questionCode": "38216-8",
      "question": "Pain severity Face FLACC",
      "answers": [
        {
          "text": "No particular expression or smile -- 0",
          "code": "LA9588-0",
          "score": 0
        },
        {
          "text": "Occasional grimace or frown, withdrawn, disinterested -- 1",
          "code": "LA9589-8",
          "score": 1
        },
        {
          "text": "Frequent to constant frown, clenched jaw, quivering chin -- 2",
          "code": "LA9590-6",
          "score": 2
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38217-6",
      "question": "Pain severity Legs FLACC",
      "answers": [
        {
          "text": "Normal position or relaxed -- 0",
          "code": "LA9591-4",
          "score": 0
        },
        {
          "text": "Uneasy, restless, tense -- 1",
          "code": "LA9592-2",
          "score": 1
        },
        {
          "text": "Kicking, or legs drawn up -- 2",
          "code": "LA9593-0",
          "score": 2
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38218-4",
      "question": "Pain severity Activity FLACC",
      "answers": [
        {
          "text": "Lying quietly, normal position, moves easily -- 0",
          "code": "LA9594-8",
          "score": 0
        },
        {
          "text": "Squirming, shifting back and forth, tense -- 1",
          "code": "LA9595-5",
          "score": 1
        },
        {
          "text": "Arched, rigid, or jerking -- 2",
          "code": "LA9596-3",
          "score": 2
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38219-2",
      "question": "Pain severity Cry FLACC",
      "answers": [
        {
          "text": "No cry (awake or asleep) -- 0",
          "code": "LA9597-1",
          "score": 0
        },
        {
          "text": "Moans or whimpers, occasional complaint -- 1",
          "code": "LA9598-9",
          "score": 1
        },
        {
          "text": "Crying steadily, screams or sobs, frequent complaints -- 2",
          "code": "LA9599-7",
          "score": 2
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "38220-0",
      "question": "Pain severity Consolability FLACC",
      "answers": [
        {
          "text": "Content, relaxed -- 0",
          "code": "LA9600-3",
          "score": 0
        },
        {
          "text": "Reassured by occasional touching, hugging, or being talked to, distractable -- 1",
          "code": "LA9601-1",
          "score": 1
        },
        {
          "text": "Difficult to console or comfort -- 2",
          "code": "LA9602-9",
          "score": 2
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "formula": {
        "name": "SCORE",
        "value": []
      },
      "questionCode": "38215-0",
      "question": "Pain severity total FLACC",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/34566-0.json
{
  "type": "LOINC",
  "code": "34566-0",
  "name": "Vital Signs Panel",
  "items": [
    {
      "questionCode": "8867-4",
      "question": "Heart rate",
      "dataType": null,
      "units": [
        {
          "name": "/min",
          "code": 5593
        },
        {
          "name": "bpm",
          "code": 5594
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9279-1",
      "question": "Respiratory rate",
      "dataType": null,
      "units": [
        {
          "name": "/min",
          "code": 5602
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "35094-2",
      "question": "Blood Pressure Panel",
      "dataType": null,
      "units": [],
      "header": true,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8480-6",
      "question": "Systolic blood pressure",
      "dataType": null,
      "units": [
        {
          "name": "mm Hg",
          "code": 5580
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8462-4",
      "question": "Diastolic blood pressure",
      "dataType": null,
      "units": [
        {
          "name": "mm Hg",
          "code": 5578
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8478-0",
      "question": "Mean blood pressure",
      "dataType": null,
      "units": [
        {
          "name": "mm Hg",
          "code": 5579
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8357-6",
      "question": "Blood pressure method",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8358-4",
      "question": "Blood pressure device Cuff size",
      "answers": [
        {
          "text": "Adult standard",
          "code": "LA11162-7"
        },
        {
          "text": "Adult large",
          "code": "LA11163-5"
        },
        {
          "text": "Thigh extra large",
          "code": "LA11164-3"
        }
      ],
      "dataType": "CNE",
      "units": [
        {
          "name": "centimeters",
          "code": 5830
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8359-2",
      "question": "Peripheral artery measurement site",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9856-6",
      "question": "Blood pressure device Institution inventory number",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9857-4",
      "question": "Blood pressure device Vendor model number",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9858-2",
      "question": "Blood pressure device Vendor serial number",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "35095-9",
      "question": "Body temperature record (for tracking ovulation)",
      "dataType": null,
      "units": [],
      "header": true,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8310-5",
      "question": "Body temperature",
      "dataType": null,
      "units": [
        {
          "name": "C",
          "code": 5565
        },
        {
          "name": "DEG",
          "code": 5566
        },
        {
          "name": "Deg C",
          "code": 5567
        },
        {
          "name": "DEG F",
          "code": 5920
        }
      ],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8326-1",
      "question": "Type of Body temperature device",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "8327-9",
      "question": "Body temperature measurement site",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9849-1",
      "question": "Body temperature device Institution inventory number",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9850-9",
      "question": "Body temperature device Vendor model number",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9851-7",
      "question": "Body temperature device Vendor serial number",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}
