=== LHNCBC/lforms-validator/lforms-form-schema-v0.1.0.json
{
  "id": "lforms-form-schema-v0.1.0#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "code": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "templateOptions": {
      "$ref": "#/definitions/templateOptions"
    },
    "items": {
      "type": "array",
      "items": {
        "$ref": "lforms-item-schema-v0.1.0.json"
      }
    }
  },
  "required": [
    "name",
    "items"
  ],
  "definitions": {
    "templateOptions": {
      "type": "object",
      "properties": {
        "showQuestionCode": {"type": "boolean"},
        "showCodingInstruction": {"type": "boolean"},
        "tabOnInputFieldsOnly": {"type": "boolean"},
        "hideCheckBoxes": {"type": "boolean"},
        "allowMultipleEmptyRepeatingItems": {"type": "boolean"},
        "allowHTMLInstructions": {"type": "boolean"},
        "useAnimation": {"type": "boolean"},
        "obrHeader": {"type": "boolean"},
        "hideHeader": {"type": "boolean"},
        "displayControl": {
          "type": ["object", "null"],
          "properties": {
            "questionLayout": {
              "$ref": "lforms-item-schema-v0.1.0.json#/definitions/questionLayout"
            }
          },
          "additionalProperties": false
        },
        "obxTableColumns": {
          "type": ["array", "null"],
          "items": {
            "$ref": "#/definitions/obxTableColumn"
          }
        },
        "obrItems": {
          "type": ["array", "null"],
          "items": {
            "$ref": "#/definitions/obrItem"
          }
        }
      },
      "additionalProperties": false
    },
    "obxTableColumn": {
      "type": "object",
      "properties": {
        "name": {
          "type": ["string", "null"]
        },
        "displayControl": {
          "type": ["object", "null"],
          "properties": {
            "colCSS": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "obrItem": {
      "type": "object",
      "properties": {
        "question": {"type": "string"},
        "dataType": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/dataType"}
          ]
        },
        "displayControl": {
          "type": "object",
          "properties": {
            "colCSS": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            },
            "css": {
              "oneOf": [
                {"type": "null"},
                {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/css"}
              ]
            }
          },
          "additionalProperties": false
        },
        "answerCardinality": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/cardinality"}
          ]
        },
        "answers": {
          "oneOf": [
            {"type": "null"},
            {"$ref": "lforms-item-schema-v0.1.0.json#/definitions/answers"}
          ]
        }
      },
      "additionalProperties": false
    }
  }
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/35088-4.json
{
  "type": "LOINC",
  "code": "35088-4",
  "name": "Glasgow Coma Score",
  "items": [
    {
      "questionCode": "9267-6",
      "question": "Glasgow coma score eye opening",
      "answers": [
        {
          "text": "No eye opening -- 1",
          "code": "LA6553-7",
          "score": 1
        },
        {
          "text": "Eye opening to pain -- 2",
          "code": "LA6554-5",
          "score": 2
        },
        {
          "text": "Eye opening to verbal command -- 3",
          "code": "LA6555-2",
          "score": 3
        },
        {
          "text": "Eyes open spontaneously -- 4",
          "code": "LA6556-0",
          "score": 4
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9268-4",
      "question": "Glasgow coma score motor",
      "answers": [
        {
          "text": "No motor response -- 1",
          "code": "LA6562-8",
          "score": 1
        },
        {
          "text": "Extension to pain -- 2",
          "code": "LA6563-6",
          "score": 2
        },
        {
          "text": "Flexion to pain -- 3",
          "code": "LA6564-4",
          "score": 3
        },
        {
          "text": "Withdrawl from pain -- 4",
          "code": "LA6565-1",
          "score": 4
        },
        {
          "text": "Localising pain -- 5",
          "code": "LA6566-9",
          "score": 5
        },
        {
          "text": "Obeys commands -- 6",
          "code": "LA6567-7",
          "score": 6
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "9270-0",
      "question": "Glasgow coma score verbal",
      "answers": [
        {
          "text": "No verbal response -- 1",
          "code": "LA6557-8",
          "score": 1
        },
        {
          "text": "Incomprehensible sounds -- 2",
          "code": "LA6558-6",
          "score": 2
        },
        {
          "text": "Inappropriate words -- 3",
          "code": "LA6559-4",
          "score": 3
        },
        {
          "text": "Confused -- 4",
          "code": "LA6560-2",
          "score": 4
        },
        {
          "text": "Oriented -- 5",
          "code": "LA6561-0",
          "score": 5
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "formula": {
        "name": "SCORE",
        "value": []
      },
      "questionCode": "9269-2",
      "question": "Glasgow coma score total",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/71457-6.json
{
  "type": "LOINC",
  "code": "71457-6",
  "name": "Erythropoiesis-stimulating agent panel",
  "items": [
    {
      "questionCode": "71458-4",
      "localQuestionCode": "ESRD.RQMT_305",
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Was Erythropoiesis-Stimulating Agent Prescribed?",
      "answers": [
        {
          "label": null,
          "code": "LA32-8",
          "text": "No",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA33-6",
          "text": "Yes",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "71464-2",
      "localQuestionCode": null,
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Date first prescribed",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "71465-9",
      "localQuestionCode": "ESRD.RQMT_306",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Date prescription changed",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "71466-7",
      "localQuestionCode": "ESRD.RQMT_975",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Date prescription stopped",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "71467-5",
      "localQuestionCode": "ESRD.RQMT_978",
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Erythropoiesis-stimulating agent prescribed",
      "answers": [
        {
          "label": null,
          "code": "LA18620-7",
          "text": "Epoetin Alfa",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA18621-5",
          "text": "Epoetin Beta",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA18622-3",
          "text": "Darbepoetin Alfa",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA46-8",
          "text": "Other",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "65818-7",
      "localQuestionCode": "RQMT_977",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Medication dose",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "71468-3",
      "localQuestionCode": "ESRD.RQMT_978",
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Medication route",
      "answers": [
        {
          "label": null,
          "code": "LA18623-1",
          "text": "Intravenous push",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA46-8",
          "text": "Other",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA9367-9",
          "text": "Oral",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA9429-7",
          "text": "Intramuscular",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA9437-0",
          "text": "Intravenous",
          "score": null,
          "other": null
        },
        {
          "label": null,
          "code": "LA9451-1",
          "text": "Subcutaneous",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/70299-3.json
{
  "type": "LOINC",
  "code": "70299-3",
  "name": "Anemia management panel",
  "items": [
    {
      "questionCode": "718-7",
      "localQuestionCode": "RQMT_303",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Hgb Bld-mCnc",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "33882-2",
      "localQuestionCode": "RQMT_304",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Collect Date XXX",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "2276-4",
      "localQuestionCode": "RQMT_307",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Ferritin SerPl-mCnc",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "33882-2",
      "localQuestionCode": "RQMT_308",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Collect Date XXX",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "2502-3",
      "localQuestionCode": "RQMT_309",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Iron Satn MFr SerPl",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "33882-2",
      "localQuestionCode": "RQMT_310",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Collect Date XXX",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "42810-2",
      "localQuestionCode": "RQMT_312",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": null,
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Hgb Retic Qn",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/59453-1.json
{
  "type": "LOINC",
  "code": "59453-1",
  "name": "Morse Fall Scale panel",
  "items": [
    {
      "questionCode": "59454-9",
      "question": "History of falling; immediate or within 3 months Morse Fall Scale",
      "answers": [
        {
          "text": "No",
          "code": "LA32-8"
        },
        {
          "text": "Yes",
          "code": "LA33-6"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "59455-6",
      "question": "Secondary diagnosis Morse Fall Scale",
      "answers": [
        {
          "text": "No",
          "code": "LA32-8"
        },
        {
          "text": "Yes",
          "code": "LA33-6"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "59456-4",
      "question": "Ambulatory aid Morse Fall Scale",
      "answers": [
        {
          "text": "Bed rest/nurse assist",
          "code": "LA13030-4"
        },
        {
          "text": "Crutches/cane/walker",
          "code": "LA13031-2"
        },
        {
          "text": "Furniture",
          "code": "LA13032-0"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "59457-2",
      "question": "Intravenous apparatus Morse Fall Scale",
      "answers": [
        {
          "text": "No",
          "code": "LA32-8"
        },
        {
          "text": "Yes",
          "code": "LA33-6"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "59458-0",
      "question": "Morse Fall Scale",
      "answers": [
        {
          "text": "Normal/bedrest/immobile",
          "code": "LA13033-8"
        },
        {
          "text": "Weak",
          "code": "LA13034-6"
        },
        {
          "text": "Impaired",
          "code": "LA13035-3"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "59459-8",
      "question": "Mental status Morse Fall Scale",
      "answers": [
        {
          "text": "Oriented to own ability",
          "code": "LA13036-1"
        },
        {
          "text": "Forgets limitations",
          "code": "LA13037-9"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "59460-6",
      "question": "Morse Fall risk total Morse Fall Scale",
      "dataType": null,
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    },
    {
      "questionCode": "59461-4",
      "question": "Morse Fall risk level Morse Fall Scale",
      "answers": [
        {
          "text": "No Risk (MFS Score 0 - 24)",
          "code": "LA13038-7"
        },
        {
          "text": "Low Risk (MFS Score 25 - 45)",
          "code": "LA13039-5"
        },
        {
          "text": "High Risk (MFS Score 50+)",
          "code": "LA13040-3"
        }
      ],
      "dataType": "CNE",
      "units": [],
      "header": false,
      "parentQuestionCode": null,
      "answerCardinality": {
        "min": "1",
        "max": "1"
      }
    }
  ]
}

=== LHNCBC/lforms-validator/test/fixtures/valid_data/46076-6.json
{
  "type": "LOINC",
  "code": "46076-6",
  "name": "MDS supplemental items section - version 2.0",
  "items": [
    {
      "questionCode": "46078-2",
      "localQuestionCode": null,
      "dataType": null,
      "header": true,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": "InterRAI holds the copyright to Version 2.0 of the RAI for long term care outside of the US. Content for MDS items in LOINC was derived from Version 2.0 of the RAI/MDS, and should not be reproduced outside of the United States without permission of InterRAI. Within the US, Version 2.0 is in the public domain.",
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Pneumococcal vaccine",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "45956-0",
      "localQuestionCode": "W3b",
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": "InterRAI holds the copyright to Version 2.0 of the RAI for long term care outside of the US. Content for MDS items in LOINC was derived from Version 2.0 of the RAI/MDS, and should not be reproduced outside of the United States without permission of InterRAI. Within the US, Version 2.0 is in the public domain.",
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Reason pneumococcal vaccine not received",
      "answers": [
        {
          "label": "1",
          "code": "LA185-1",
          "text": "Not eligible",
          "score": null,
          "other": null
        },
        {
          "label": "2",
          "code": "LA186-9",
          "text": "Offered and declined",
          "score": null,
          "other": null
        },
        {
          "label": "3",
          "code": "LA187-7",
          "text": "Not offered",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": "46078-2"
    },
    {
      "questionCode": "45955-2",
      "localQuestionCode": "W3a",
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": "InterRAI holds the copyright to Version 2.0 of the RAI for long term care outside of the US. Content for MDS items in LOINC was derived from Version 2.0 of the RAI/MDS, and should not be reproduced outside of the United States without permission of InterRAI. Within the US, Version 2.0 is in the public domain.",
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Pneumococcal vaccine status up to date",
      "answers": [
        {
          "label": null,
          "code": "LA1-0",
          "text": "UTD",
          "score": null,
          "other": null
        },
        {
          "label": "0",
          "code": "LA32-8",
          "text": "No",
          "score": null,
          "other": null
        },
        {
          "label": "1",
          "code": "LA33-6",
          "text": "Yes",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": "46078-2"
    },
    {
      "questionCode": "45952-9",
      "localQuestionCode": "W1",
      "dataType": null,
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": "InterRAI holds the copyright to Version 2.0 of the RAI for long term care outside of the US. Content for MDS items in LOINC was derived from Version 2.0 of the RAI/MDS, and should not be reproduced outside of the United States without permission of InterRAI. Within the US, Version 2.0 is in the public domain.",
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "National provider ID",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "46077-4",
      "localQuestionCode": null,
      "dataType": null,
      "header": true,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": "InterRAI holds the copyright to Version 2.0 of the RAI for long term care outside of the US. Content for MDS items in LOINC was derived from Version 2.0 of the RAI/MDS, and should not be reproduced outside of the United States without permission of InterRAI. Within the US, Version 2.0 is in the public domain.",
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Influenza vaccine",
      "answers": null,
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": null
    },
    {
      "questionCode": "45954-5",
      "localQuestionCode": "W2b",
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": "InterRAI holds the copyright to Version 2.0 of the RAI for long term care outside of the US. Content for MDS items in LOINC was derived from Version 2.0 of the RAI/MDS, and should not be reproduced outside of the United States without permission of InterRAI. Within the US, Version 2.0 is in the public domain.",
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Reason influenza virus vaccine not received",
      "answers": [
        {
          "label": "1",
          "code": "LA183-6",
          "text": "Not in facility during this year's flu season",
          "score": null,
          "other": null
        },
        {
          "label": "2",
          "code": "LA184-4",
          "text": "Received outside of this facility",
          "score": null,
          "other": null
        },
        {
          "label": "3",
          "code": "LA185-1",
          "text": "Not eligible",
          "score": null,
          "other": null
        },
        {
          "label": "4",
          "code": "LA186-9",
          "text": "Offered and declined",
          "score": null,
          "other": null
        },
        {
          "label": "5",
          "code": "LA187-7",
          "text": "Not offered",
          "score": null,
          "other": null
        },
        {
          "label": "6",
          "code": "LA188-5",
          "text": "Inability to obtain vaccine",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": "46077-4"
    },
    {
      "questionCode": "45953-7",
      "localQuestionCode": "W2a",
      "dataType": "CNE",
      "header": false,
      "units": null,
      "formula": null,
      "codingInstructions": null,
      "copyrightNotice": "InterRAI holds the copyright to Version 2.0 of the RAI for long term care outside of the US. Content for MDS items in LOINC was derived from Version 2.0 of the RAI/MDS, and should not be reproduced outside of the United States without permission of InterRAI. Within the US, Version 2.0 is in the public domain.",
      "questionCardinality": null,
      "answerCardinality": null,
      "question": "Influenza virus vaccine received in facility",
      "answers": [
        {
          "label": null,
          "code": "LA1-0",
          "text": "UTD",
          "score": null,
          "other": null
        },
        {
          "label": "0",
          "code": "LA32-8",
          "text": "No",
          "score": null,
          "other": null
        },
        {
          "label": "1",
          "code": "LA33-6",
          "text": "Yes",
          "score": null,
          "other": null
        }
      ],
      "skipLogic": null,
      "restrictions": null,
      "editable": null,
      "defaultAnswer": null,
      "formatting": null,
      "calculationMethod": null,
      "parentQuestionCode": "46077-4"
    }
  ]
}
